version: '3.9'

services:
  dbc_postgres_local:
    image: postgres:14-alpine
    container_name: postgres_local_db
    ports:
      - "35432:5432"
    volumes:
      - ~/src/dbc/common-lib/postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=dbc_test